# Generated by Django 2.2.4 on 2019-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
